# Generated by Django 5.1.1 on 2024-09-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KenetAssets', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('serial_number', 'receiving')},
        ),
    ]
