# Generated by Django 5.1.1 on 2024-09-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KenetAssets', '0002_alter_asset_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='receiving',
            unique_together={('serial_number', 'consignment')},
        ),
    ]
