# Generated by Django 5.1.1 on 2024-09-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KenetAssets', '0003_alter_receiving_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('in_use', 'In Use'), ('available', 'Available'), ('maintenance', 'Maintenance'), ('decommissioned', 'Decommissioned')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='status',
            field=models.CharField(choices=[('testing', 'Testing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
