# Generated by Django 5.1.1 on 2024-09-04 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KenetAssets', '0004_asset_status_alter_receiving_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KenetAssets.location'),
        ),
    ]
